name: aspire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  animations: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
   - assets/Profile.png
   - assets/Content.png
   - assets/Graph.png
   - assets/Onboarding2.png
   - assets/Onboarding3.png
   - assets/header_bg.png
   - assets/balance.jpg
   - assets/personality.jpg
   - assets/interests.jpg
   - assets/skillsandaptitudes.jpg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: 
    "assets/Logo.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo2.png"