name: aspire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  animations: ^2.1.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_ai: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  assets:
   - assets/Profile.png
   - assets/Content.png
   - assets/Graph.png
   - assets/Onboarding2.png
   - assets/Onboarding3.png
   - assets/header_bg.png
   - assets/balance.png
   - assets/personality.png
   - assets/interests.png
   - assets/skillsandaptitudes.png
   - assets/get_started_bg.png
   - assets/login_background.png
   - assets/interests_heropage.png
   - assets/Appbar.png
   - assets/Card.png
   - assets/Card2.png
   - assets/Job Card.png
   - assets/Chart.png
   - assets/personalityandworkstyle_heropage.png
   - assets/skillsandaptitudes_heropage.png
   - assets/workvalues_heropage.png
   - assets/quiz_results/Analytical-Logic.png
   - assets/quiz_results/Artistic.png
   - assets/quiz_results/Communication.png
   - assets/quiz_results/Conventional.png
   - assets/quiz_results/Enterprising.png
   - assets/quiz_results/Investigative.png
   - assets/quiz_results/Leadership.png
   - assets/quiz_results/Realistic.png
   - assets/quiz_results/Social.png
   - assets/quiz_results/Tech-Digital.png
   - assets/quiz_results/Creative-Design.png
   - assets/quiz_results/High-Income.png
   - assets/quiz_results/Helping-Society.png
   - assets/quiz_results/Work-Life-Balance.png
   - assets/quiz_results/Creativity-Freedom.png
   - assets/quiz_results/Abstract.png
   - assets/quiz_results/Collaborative.png
   - assets/quiz_results/Concrete.png
   - assets/quiz_results/Independent.png
   - assets/quiz_results/Risk-Taker.png
   - assets/quiz_results/Stability-Security.png
   - assets/career_card_bg.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: 
    "assets/Logo.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo2.png"